services:
  go-service:
    build: ./backend/go-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    # optional dev hot-reload (see note below)
    # volumes:
    #   - ./backend/go-service:/app

  python-service:
    build: ./backend/python-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/python-service:/app
    env_file:
      - ./backend/python-service/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    hostname: vocabulary-app
    container_name: vocabulary-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules